### ISSUE TITLE
git工作流-基础

### ISSUE THREAD

**Issue by bitjian** [bitjian/learn_note#10]
## 1.创建工作流路径和工作流文件
``` bash
mkdir .github && mkdir mkdir .github/workflows
touch xxx.yml
```

## 2.熟悉工作流常用语法
> 1 name 指定工作的名称
```yml
name： react-action-deploy
```
> 2 on 指定触发工作流的事件
```yml
on: push
```
> 2.1 on 也可以指定多个事件
```yml
on: [push, pull_request]
```
> 2.2 on 指定分支触发
```yml
on:
  push:
    branches:    
      - master
```
> 3.jobs.<job_id>.name 指定工作流热任务名称
```yml
jobs:
  my_first_job:
    name: My first job
  my_second_job:
    name: My second job
```
> 4.jobs.<job_id>.runs-on 指定任务运行的系统环境
```yml
jobs:
  my_first_job:
    name: My first job
   runs-on:  ubuntu-latest
  my_second_job:
    name: My second job
    runs-on: windows-latest
```
> 5.jobs.<job_id>.steps 任务的运行步骤
> steps字段指定每个 Job 的运行步骤，可以包含一个或多个步骤。每个步骤都可以指定以下三个字段。  
```
jobs.<job_id>.steps.name：步骤名称。
jobs.<job_id>.steps.run：该步骤运行的命令或者 action。
jobs.<job_id>.steps.env：该步骤所需的环境变量。
jobs.<job_id>.steps.uses: 使用其他的工作步骤， 例如actions/checkout@v4 复制github代码到 runs-on 的环境上, JamesIves/github-pages-deploy-action@v4 部署页面到gitpage
jobs.<job_id>.steps.with: 携带步骤的参数
```
## 3 部署react项目到gitpage
> 1 permissions: write 记得带上这个，不然部署可能会出错  
> 2 需要再package 加上homepage路径，不然发布访问gitpage会找不到静态资源路径而报错  
```
"homepage": ".",
```
> 3 在git项目的`Settings-Pages` 打开gitpage功能
![image](https://github.com/user-attachments/assets/af99bc76-de7f-4828-978c-44c67ac37201)

```yml
name: react打包发布
on: push

permissions: 
  contents: write
jobs:
  npm-run-build:
    name: npm-build工作
    runs-on: ubuntu-latest
    
    steps:
    - name: 复制仓库内容
      uses: actions/checkout@v4
    - name: 安装依赖和打包
      run: |
        npm install
        npm run build
    - name: 部署
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: build
```
## 4 打包react项目并部署到dockerhub上
> 1.前往dockerhub 创建一个仓库 `create repository`
![image](https://github.com/user-attachments/assets/39c79bda-8080-42b6-85dc-c4db4d3eae32)
> 2. 前往dockerhub - account settings 创建私钥， 并设置`读写`权限,复制私钥
![image](https://github.com/user-attachments/assets/7282ab85-57b3-4ddc-a117-de9ff5353266)
> 3. 前往 github- 创建的仓库 settings 设置 dockerhub私钥  
![image](https://github.com/user-attachments/assets/b0066587-76a8-44df-9610-e75c078d2cbd)
> 4. 本地项目创建 Dockerfile 文件，并编写基本的打包命令
```dockerfile
from node:18-alpine

WORKDIR /react-app

copy public /react-app/public
copy src /react-app/src
copy package.json /react-app/package.json

run npm install
CMD [ "npm", "start" ]
```
> 5. 修改github工作流的yml文件
```yml
name: react打包发布
on: push

jobs:
  npm-run-build:
    name: npm-build工作
    runs-on: ubuntu-latest

    steps:
    - name: 复制仓库内容
      uses: actions/checkout@v4

    - name: 登陆docker-hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERNAME }}
        password: ${{ secrets.DOCKERPASS }}
    
    - name: 构建并推送到docker-hub
      uses: docker/build-push-action@v5
      with: 
        push: true
        tags:  zzj1183048003/react-action-test:latest
```
